### ISSUE TITLE
yesod-recaptcha2-0.2.3 build failure with yesod-1.6

### ISSUE THREAD

**Issue by DanBurton** [ncaq/yesod-recaptcha2#2]
As seen on the Stackage build server:

```
Building library for yesod-recaptcha2-0.2.3..

[1 of 1] Compiling Yesod.ReCaptcha2 ( src/Yesod/ReCaptcha2.hs, dist/build/Yesod/ReCaptcha2.o )

src/Yesod/ReCaptcha2.hs:37:15: error:
    • Variable not in scope:
        liftHandlerT
          :: HandlerFor site0 (FormResult ())
             -> transformers-0.5.2.0:Control.Monad.Trans.RWS.Lazy.RWST
                  (Maybe (Env, FileEnv), site, [Lang])
                  Enctype
                  Ints
                  (HandlerT site IO)
                  (FormResult ())
    • Perhaps you meant ‘liftHandler’ (imported from ClassyPrelude.Yesod)
   |
37 |     result <- liftHandlerT formResult
   |               ^^^^^^^^^^^^
```

**Comment by DanBurton** [comment]
I've removed yesod-recaptcha2 from the Stackage nightly build plan, and unfortunately it won't appear in the initial LTS 11 release.

To get back into nightly, open a PR on the Stackage repo as usual. To get into LTS 11, open an issue on https://github.com/fpco/lts-haskell/issues.

**Comment by DanBurton** [comment]
n.b. I was able to reproduce this error locally like so:

```bash
stack unpack yesod-recaptcha2-0.2.3 && cd yesod-recaptcha2-0.2.3
edit stack.yaml # add the following stack.yaml
stack build
```

```yaml
# stack.yaml
resolver: nightly-2018-03-10
extra-deps:
- yesod-1.6.0
- yesod-core-1.6.2
- yesod-form-1.6.1
- conduit-1.3.0
- conduit-extra-1.3.0
- resourcet-1.2.0
- xml-conduit-1.8.0
- http-conduit-2.3.0
- classy-prelude-yesod-1.4.0
- classy-prelude-conduit-1.4.0
- classy-prelude-1.4.0
- yesod-auth-1.6.0
- yesod-newsfeed-1.6.1.0
- yesod-persistent-1.6.0
- yesod-static-1.6.0
- persistent-2.8.1
```
